name: Blanket CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Clean Project
        run: ./scripts/clean.sh
      - name: Validate Project
        run: ./scripts/validate.sh

  build_android:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Build Android App
        run: ./scripts/build-android.sh
      - name: Upload Android APKs and AABs
        uses: actions/upload-artifact@v4
        with:
          name: blanket-android-builds
          path: |
            composeApp/build/outputs/**/*.apk
            composeApp/build/outputs/**/*.aab

  build_ios:
    needs: lint_and_test
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build iOS app
        uses: cartland/xcodebuild@v3.6.0
        with:
          xcode: ^16
          scheme: iosApp
          platform: iOS
          action: build
          derived-data-path: build
          working-directory: iosApp

      - name: Upload iOS App
        uses: actions/upload-artifact@v4
        with:
          name: blanket-ios-app
          path: iosApp/build/

  build_desktop:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Build Desktop App
        run: ./scripts/build-desktop.sh
      - name: Upload Desktop JAR
        uses: actions/upload-artifact@v4
        with:
          name: blanket-desktop-jar
          path: composeApp/build/compose/jars/

  build_wasm:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Build WasmJS
        run: ./scripts/build-wasm.sh
      - name: Upload WasmJS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: blanket-wasm-dist
          path: |
            composeApp/build/dist/wasmJs/productionExecutable

  build_server:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Build Server
        run: ./scripts/build-server.sh
      - name: Upload Server JAR
        uses: actions/upload-artifact@v4
        with:
          name: blanket-server-jar
          path: server/build/libs/
