name: Blanket CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Validate Project
        run: ./scripts/validate.sh

  build_android:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Android App
        run: ./scripts/build-android.sh
      - name: Upload Android APKs and AABs
        uses: actions/upload-artifact@v4
        with:
          name: blanket-android-builds
          path: |
            composeApp/build/outputs/**/*.apk
            composeApp/build/outputs/**/*.aab

  build_ios:
    needs: lint_and_test
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build iOS app
        uses: mxcl/xcodebuild@v3
        with:
          xcode: ^16
          scheme: iosApp
          platform: iOS # Changed from 'iOS Simulator' to 'iOS'
          action: build
          derived_data_path: iosApp/build # Explicitly set DerivedData path
          working-directory: iosApp # Added working directory

      - name: Upload iOS App
        uses: actions/upload-artifact@v4
        with:
          name: blanket-ios-app
          path: iosApp/build/ # This path should now be correct

  build_desktop:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Desktop App
        run: ./scripts/build-desktop.sh
      - name: Upload Desktop JAR
        uses: actions/upload-artifact@v4
        with:
          name: blanket-desktop-jar
          path: composeApp/build/compose/jars/

  build_wasm:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build WasmJS
        run: ./scripts/build-wasm.sh
      - name: Upload WasmJS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: blanket-wasm-dist
          path: composeApp/build/dist/wasmJs/production/

  build_server:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Server
        run: ./scripts/build-server.sh
      - name: Upload Server JAR
        uses: actions/upload-artifact@v4
        with:
          name: blanket-server-jar
          path: server/build/libs/
